language: python
python:
  - 3.7

services:
  - docker

install:
  - docker build -t python-app .
  - docker run -d -p 80:80 --name python-app python-app

before_script:
  - pip install -r requirements.txt

script:
  - docker ps | grep -q blog
  - python app/tests.py

after_success:
  - heroku container:login
  - heroku container:release web -a yusrapythonapp
  - heroku container:release web -a yusrapythonapp